 
    <div class="fbg_resize">
      <div class="col c1">
        <h2><span>Image Gallery</span></h2>
        <a><img src="images/pic_1.jpg" width="58" height="58" alt="" /></a> <a><img src="images/pic_2.jpg" width="58" height="58" alt="" /></a> <a ><img src="images/pic_3.jpg" width="58" height="58" alt="" /></a> <a ><img src="images/pic_4.jpg" width="58" height="58" alt="" /></a> <a ><img src="images/pic_5.jpg" width="58" height="58" alt="" /></a> <a ><img src="images/pic_6.jpg" width="58" height="58" alt="" /></a> </div>
      <div class="col c2">
        <h2><span>BlaBLaApp</span></h2>
        <p>
          Abbiamo reso veramente facile per le persone creare un blog e metterci dentro quello che vogliono.

            BlaBlaApp è fatto dai blog. Succede che quando rendi estremamente facile creare contenuti interessanti, le persone fanno esattamente quello. Tutti quei blog meravigliosi che ti mandano i tuoi amici, sono blog BlaBlaApp. Ti aiuteremo a trovare e seguire blog meravigliosi, e aiuteremo altre persone a trovare e seguire il tuo.</p>
      </div>
      <div class="col c3">
        <h2><span>About</span></h2>
        <p>Quando segui un blog, puoi vedere tutti i suoi post nella tua dashboard, proprio come ti aspetti. Vedi qualcosa di spettacolare? Aggiungi un commento se ti va. Fallo tuo. Altre persone faranno lo stesso con i tuoi post. È così che si conosce gente in questo posto. </p>
      </div>
      <div class="clr"></div>
    </div>
 