<br /><br />
<div id="view-content">
	
    <div class="content">
      <div class="content_bg">
        <center>
          <div class="article">
            <h1>BlaBlaApp è così facile da usare che è difficile da spiegare.</h1>
            <div class="clr"></div>
           
            <img class="presentationImage" src="images/serveimage.png"  alt=""/>
            <p class="description">Abbiamo reso veramente facile per le persone creare un blog e metterci dentro quello che vogliono.</p>
			<p class="description">BlaBlaApp è fatto dai blog.

			Succede che quando rendi estremamente facile creare contenuti interessanti, le persone fanno esattamente quello. Tutti quei blog meravigliosi che ti mandano i tuoi amici, sono blog BlaBlaApp. Ti aiuteremo a trovare e seguire blog meravigliosi, e aiuteremo altre persone a trovare e seguire il tuo.
            
            sitemap:<a href="<?php echo $this->baseUrl('css/BlaBlaApp.pdf');?>">documentazione sito</a>
			  </p>
			  
            
			<h1>Vieni per quello che ami.
											Resta per quello che scopri.
											</h1>
			 <br/>
			  
			<p class="description">Quando segui un blog, puoi vedere tutti i suoi post nella tua dashboard, proprio come ti aspetti. Vedi qualcosa di spettacolare? Aggiungi un commento se ti va. Fallo tuo. Altre persone faranno lo stesso con i tuoi post. È così che si conosce gente in questo posto.
			</p>
			</center>
			  
            <div class="clr"></div>
          </div>
          
        
       
        <div class="clr"></div>
      </div>
    </div>
	<br/>
	<br/>
	<div class="fbg">
    
  		<?= $this->render('_fbg.phtml') ?>
  	</div>
	
  </div>

