<ul>
	<li id="HomeNavLi" ><a href=" <?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Gestione Utenti</a></li>
	
	
          <!--<li><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'aboutus',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Chi siamo</a></li>-->
	
          <li id="WhereNavLi"><a href=" <?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'where',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Dove siamo</a></li>
		
		<li id="ContactNavLi"><a href=" <?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'contactus',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Contattaci</a></li>
	
          <li ><a href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'logout',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Logout</a></li>
        </ul>
		  <div class="clr"></div>

    