<ul>
    
    
	<li class="active"><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Home</a></li>
	
	
          <!--<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'aboutus',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Chi siamo</a></li>-->
	
          <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'where',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Dove siamo</a></li>
		
		<li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'contactus',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Contattaci</a></li>
	
          <li><a href=" <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                        ), 
                        'default',true
                    ); 
                 ?>"
		title="Home">Login</a></li>
        </ul>
		  <div class="clr"></div>
<div class="hbg"><img src="images/header_images.jpg" width="923" height="291" alt="" /></div>
    