<?php echo $this->doctype() ?>
<html>
<head>
	<base href="<?= $this->baseUrl().'/'; ?>" >
	<?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
</head>
<body>
	<script src="<?php echo $this->baseUrl('js/jquery-1.12.4.js');?>"></script>	
    <script src="<?php echo $this->baseUrl('js/jquery-ui.js');?>"></script>
  <link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery-ui.css');?>">
  <link rel="stylesheet" href="/resources/demos/style.css">
	<script type="text/javascript">
		
		$(function(){
			
			$('#s').bind('focus',function(){
				
				if ($(this).val() == 'Search...')
					$(this).val('');
			});
			
			$('#s').bind('keyup',function(){
				if ($(this).val() == '')
					$('#resultss').html('');
                
				search($(this).val());
                
			});
			
		});
		
		function search( value )
		{
            
			var obj = {'value':value };
			
			var url = ' <?= $this->url(array('controller' => 'user', 'action' => 'search',), 'default') ?> ';
			
			$.ajax({

            type : 'POST',
            url  : url,
            data : obj,
			dataType: 'json',
            beforeSend: function()
            {
                
            },
			 success :  function(data)
            {
                if(data=="error"){
						$('#resultss').val('');
                    alert(data);
                    
                }
                else if(true)
                {
					
					$('#resultss').html('');
						for(var i in data){
                            if (data[i][3] == 1 ){   // friends already
                                $('#resultss').append(
                                        '<div max_widht =110px"><img class="comment_pic" align ="top" width="30" height="30" alt="" src="'+data[i][4]+'" ><span >'+data[i][0]+' '+ data[i][1]+'</span></br> <button onclick = "return visitaprofilo(\''+ data[i][5]+'\' )">profilo</button></div><br>'	
                                    
							
					);}
                        
                        else if(data[i][3] == -1 && data[i][2] == "0" ){ //not friends but request already sent && public profile
                            
                                $('#resultss').append(
                                        '<div max_widht =110px"><img class="comment_pic" align ="top" width="30" height="30" alt="" src="'+data[i][4]+'" ><span >'+data[i][0]+' '+ data[i][1]+'</span></br><button disabled = "true">richiesta inviata</button> <button onclick = "return visitaprofilo(\''+ data[i][5]+'\' )">profilo</button></div><br>'	
                                    
							
					           );
                        }
                        
                        else if (data[i][3] == -1 && data[i][2] == "1"){ // not friends but request already sent && not public profile
                            $('#resultss').append(
                                        '<div max_widht =110px"><img class="comment_pic" align ="top" width="30" height="30" alt="" src="'+data[i][4]+'" ><span >'+data[i][0]+' '+ data[i][1]+'</span></br> <button disabled="true">richiesta inviata</button></div><br>'	
							
							
					);}
                        
                        else if (data[i][2] == "1"){ // not friends && not public profile
                            $('#resultss').append(
                                        '<div max_widht =110px"><img class="comment_pic" align ="top" width="30" height="30" alt="" src="'+data[i][4]+'" ><span >'+data[i][0]+' '+ data[i][1]+'</span></br> <button onclick ="return friendRequest(this,\''+data[i][5]+'\')">aggiungi</button></div><br>'	
							
							
					);}
                        
                        else{
                            $('#resultss').append( //not friends and public profile
                                        '<div max_widht =110px"><img class="comment_pic" align ="top" width="30" height="30" alt="" src="'+data[i][4]+'" ><span >'+data[i][0]+' '+ data[i][1]+'</span></br> <button onclick ="return friendRequest(this,\''+data[i][5]+'\')">aggiungi</button><button onclick = "return visitaprofilo(\''+ data[i][5]+'\' )">profilo</button></div><br>');
                            
                            }
                        }
									
									
                }
				else{
					
					
					alert(data);
				}
                
            }
        });
		}
        
        function visitaprofilo( usr ){
            
            var url = ' <?= $this->url(array('controller' => 'staff', 'action' => 'profile',), 'default') ?>';
            location.href = url+'/usr/'+usr;
        }
        
        
        
        
    
    
		
	</script>
	<!--start header -->
	<div class="main">
  <div class="main_resize">
    <div class="header">
      <div class="logo">
        <h1><a><span>BlaBla</span>App<small>Social Community</small></a></h1>
      </div>
      <div class="search">
       
		  <div id="resultss"></div>
        <!--/searchform -->
        <div class="clr"></div>
      </div>
		
      <div class="clr"></div>
	  <!--end header -->
		
		
	  <!--start navmenu -->
	  <div class="menu_nav">
       <?= $this->render('_topNavStaffMenu.phtml') ?>
      </div>
	</div>
		<!--end navmenu -->
		
		<!--content -->
		<div id="content">
  	  	<?php echo $this->layout()->content; ?>
      	<div style="clear: both;">&nbsp;</div>
		</div>
	 </div>

		<!-- end #content -->
		<!--footer-->
		<div class="footer">
		  <div class="footer_resize">
			<p class="lf">Copyright &copy; <a href="#">Domain Name</a>. All Rights Reserved</p>
			<p class="rf">Design by <a target="_blank" >Giorgio Aurispa</a></p>
			<div class="clr"></div>
		  </div>
		</div>

		
</body>