
<script type="text/javascript">

    $(function()
{
	
	$("#profiForm").submit(function(event){
        event.preventDefault();
        var data = new FormData($('#profiForm')[0]);
        
        
		submitProfiForm(data);
        });
		
		
	});

    
    
        
    	function submitProfiForm(dataset)
    {
        
		var url = ' <?= $this->url(array('controller' => 'user', 'action' => 'ajaxupdateuserinfo',), 'default') ?> ';
        $.ajax({

            type : 'POST',
            url  : url,
            data : dataset,
            processData: false,
            contentType: false,
            
            beforeSend: function()
            {
                $("#infomessage").html('inviando i dati...');
                
            },
            success :  function(data)
            {
                if(data == 'non puoi nascere nel futuro'){
						$("#infomessage").html(data);
                    
                }
                
                else if(data=="OK")
                {

                    $("#infomessage").html('dati aggiornati');
                }
				else{
                    
                    $("#infomessage").html('alcuni dati inseriti non vanno bene');
                    
					
                    $.each(data, function(i, item) {
                        
                        $("#"+i).parent().parent().find('.errors').html(' ');
                        $("#"+i).parent().parent().find('.errors').html(getErrorHtml(item));
                    });				
                
                }
                
            }
        });
        return false;
    }
    
    function getErrorHtml(formErrors)
{
	if((typeof(formErrors) === 'undefined') || (formErrors.length < 1)) return;
	
	var out = '<ul>';
	for(errorKey in formErrors) {
        out += '<li>' + formErrors[errorKey] + '</li>';
    }
    out += '</ul>';
    return out;
}
    
	function showupdateInfoPanel()
	{
		$("#updateInfoPanel").toggle();
		$('#infomessage').html('');
		
		
		return false;
		
	}
    
	$(function(e){
		
		$("#invisibilityCheckbox").change(function(e) {
    // this will contain a reference to the checkbox 
		var url = ' <?= $this->url(array('controller' => 'user', 'action' => 'togglevisibility',), 'default') ?> ';
			
    if (this.checked) {
		var obj = {'visibility':'true' };
      
    } else {
        var obj = {'visibility':'false' };
    }
			
	$.ajax({

            type : 'POST',
            url  : url,
            data : obj,
            beforeSend: function()
            {
				
                
                
            },
			 success :  function(data)
            {
                if(data=="error"){
						
						$(this).parent().prepend('Connessione assente?');
                    
                }
                else if(data=="OK")
                {
					
					
                }
				else{				
					
					
				}
                
            }
        });
			return false;
			
});
	});
	
	
	
	

</script>

<?php if (null !== $this->usrData)
{
    $username = $this->usrData->username;
	$name = $this->usrData->name;
	$surname = $this->usrData->surname;
	$description = $this->usrData->description;
    $profipicture = $this->usrData->profipic;
	$isMyProfile=false;
	
}else{
    $username = $$this->authInfo('username');
	$name = $this->authInfo('name');
	$surname = $this->authInfo('surname');
	$description = $this->authInfo('description');
    $profipicture = this->authInfo('profipic');
	$isMyProfile=true;
};?>


<div class="gadget">
            <h2 class="star"><span>Log</span> Info</h2>
			<br>
            <div class="clr"></div>
			<div id="logInfo"  >
				
				<img class="profipic" width="55" height="58" alt="" align ="middle" 
                     
                     src="<?=$this->PostImgHelper($profipic,$username=$username?>" />
				
					<span class="name" size="6px"><?php echo  $name.' '.  $surname; ?><br>
					<?php if($isMyProfile){
						echo '
							<span class="tinyline"><a href="#" onclick="return showupdateInfoPanel()">cambia info</a></span><br>
							<span class="tinyline">logout</span>
							';
							}?></span>
				
				
			<div id="updateInfoPanel" class="popup-position" hidden="hidden">
		<div class="popup-wrapper">
			<div class="popup-container">
				<div id="infomessage"></div>
				<?=$this->profiForm; ?>
					
			<a href="#" onclick="return showupdateInfoPanel()" class="tinyline">esci</a>
			</div>

		</div>
	</div>
				
					
				
			</div>
	<!-- Rounded switch -->
	<br><br>
	<span align="middle">profilo nascosto:</span>
    <? if($isMyProfile):?>
	<label class="switch">
	  <input autocomplete="off" id="invisibilityCheckbox" type="checkbox" <?php if($this->authInfo('hidden')) echo 'checked' ?> >
	  <div class="slider round"></div>
	</label>
    <? endif;?>
			<br>  <br>      
           </div>

		<div class="gadget">
            <h2 class="star"><span>Mi presento</span></h2>
            <div class="clr"></div>
            <div class="testi">
              <p><span class="q"><img src="images/qoute_1.gif" width="20" height="15" alt="" /></span> <?php echo $description; ?>. <span class="q"><img src="images/qoute_2.gif" width="20" height="15" alt="" /></span></p>
              
            </div>
          </div>