<script type="application/javascript">
$(function(){
$('#ContactNavLi').addClass('active');
});
</script>

<br /><br />
<div id="view-content">
	<div class="title">
			<h2>I Nostri <span class="byline">Contatti</span></h2>
		</div>
		<p>Via Brecce Bianche, 12<br />
        60131 Ancona (AN)</p>
        
        <p>Telefono: 333-123456<br>
           Fax:071-123456</p>
        <p> Email:  <a href="mailto:jaws24@hotmail.it">jaws24@hotmail.it</a></p></p>
</div>