
<script type="text/javascript">
    
    $(function(){
        
        $('#HomeMenuLi,#HomeNavLi').addClass('active');
        checkNotification();
        
        $('.commentTextArea').bind('keyup',function (e){
	
	if(e.keyCode==13)
		{
			var element = $(this);
			var comment =$(this).val();
            var srcPic = element.parent().find('.comment_pic').attr('src');
            var nameCommentor = element.parent().find('.comment_pic').attr('alt');
			//alert($(this).attr('id'));
			var obj = {'comment':$(this).val(),'id_post':$(this).attr('id') };
            
			var url = ' <?= $this->url(array('controller' => 'user', 'action' => 'comment',), 'default') ?> ';
			
			
		$.ajax({

            type : 'POST',
            url  : url,
            data : obj,
            beforeSend: function()
            {
                $('.commentTextArea').attr("disabled","true");
                
            },
			 success :  function(data)
            {
                if(data=="error"){
						$(this).parent().parent().prepend('Connessione assente?');
                    
                }
                else if(data=="OK")
                {
					$('.commentTextArea').val('');
					$('.commentTextArea').prop('disabled', false);

                     element.parent().find('.comments').prepend('<div max_widht ="90px"><img class="comment_pic" align ="middle"width="30" height="30" alt="" src="'+srcPic+'" ><a href="/BlablaApp/public/index.php/user/index"><span class="nameComment">'+nameCommentor+' </span></a><span >'+comment+'</span></div><br>');
                }
				else{
					
					
					alert(data);
				}
                
            }
        });
			return false;
		}
        
    });
});
    
    function checkNotification()
    {
        var url = ' <?= $this->url(array('controller' => 'user', 'action' => 'checknotification',), 'default') ?> ';
          $.ajax({

            type : 'POST',
            url  : url,
            success :  function(data)
            {
                if(data=="error"){
						//$("#erroremessage").html('Alcuni dati inseriti non vanno bene');
                    
                }
                else if(data >=1)
                {
                    $('#NotificheMenuLi').find('a').html('Notifiche ' +data);
                    $('#NotificheMenuLi').addClass('active');
                    
                }
                
            }
        });
    }
        
    function showCommentSection(selector){
        $(selector).parent().parent().find('.commentSection').toggle();
    }
    
    
    </script>



<?php $name= $this->authInfo('name') ;
		$surname = $this->authInfo('surname'); 

?>

<br /><br />
<div id="view-content">
	
    <div class="content">
      <div class="content_bg">
        <div class="mainbar">
            <?php if (count($this->Posts) ==0) :?>
            <p>NewsFeed vuoto :(</p>
            <?php endif; ?>
          <?php foreach ($this->Posts as $post) :?>
          <div class="article" id = "<?=$post->id_post?>" >
            <h2><span><?php echo $post->title; ?></span></h2>
            <div class="clr"></div>
              <p class="post-data"><span class="date"><?php echo date('d M Y H:i', $post->timestamp); ?></span> &nbsp;|&nbsp; Postato da <a href="#"><?php echo $post->username; ?></a>
                  
                  
              
              </p>
              
			<?php if ($post->photo_name != null) echo $this->PostImgHelper($post->photo_name); ?>
            <!--<img src="images/images_1.jpg" width="613" height="193" alt="" /> -->
            <p>	<?php echo $post->post_text; ?>	 </p>
            <p class="spec"><!--<a onclick="return showCommentSection(this);" class="com fr">Commenti</a>-->
            <?php   
                $urlPostView = $this->url(array('controller' => 'user', 'action' => 'singlepost','postId'=> $post->id_post,'blogId'=>$post->blog_id), 'default');
                ?>    
            <a href="<?=$urlPostView?>" class="rm fl">Leggi di più</a></p>
			 <br>	
			 	<div class="commentSection" hidden="hidden">
					<hr>
					<img class="comment_pic" width="30" height="30" 
                         alt="<?=$this->authInfo('name').' '.$this->authInfo('surname') ?>" 
                         src="<?=$this->PostImgHelper($this->authInfo('profipic'),$this->authInfo('username')) ?>" 
                    >
						<textarea  id="<?= $post->id_post?>" class="commentTextArea" cols="65" rows="1"></textarea>
					<div class="comments">
					<?php $comments =$this->CommentHelper($post->id_post);?>
					<?php foreach ($comments as $comment) :?>
					<div class="single_comment" >
                        <?php $userData = $this->FriendHelper($comment->username);
                        $urlUsrProfile =$this->url(array('controller' => 'user', 'action' => 'profile','usr'=> $userData->username), 'default');
                        ?>
						<div max_widht ="90px"><img class="comment_pic" align ="middle"width="30" height="30" alt="" src="<?=$this->PostImgHelper($userData->profipic,$userData->username) ?>" >
                            
                            <a href="<?=$urlUsrProfile?>"> <span class="nameComment"><?=$userData->name.' '.$userData->surname ?></span> </a>
                            <span ><?= $comment->comment?></span></div><br>
						
			 		</div>
					<?php endforeach?>
			  		</div>
			 	</div>
			  
            <div class="clr"></div>
              <br>
          </div>
			
			<?php endforeach?>
			
			 <?php if($this->Posts instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->Posts,'Sliding','user/_indexPaginator.phtml');
			  } 
			  ?>

        </div>
        <div class="sidebar">
		<?= $this->render('_sideLog.phtml') ?>
     	<?= $this->render('_sideBar.phtml') ?>
        </div>
        <div class="clr"></div>
      </div>
    </div>
	<div class="fbg">
    
  		<?= $this->render('_fbg.phtml') ?>
        
  	</div>
	
  </div>

