<script type="application/javascript">
$(function(){
$('#WhereNavLi').addClass('active');
});
</script>

<br /><br />
<div id="view-content">
	<div class="static">
  <br>
  <center><h1>Chi Siamo</h1><br/>
	<p class="description">
		BlaBblaApp &egrave un portale che permette ad ogni utente di creare il prprio personalissimo blog(o anche più di uno).
		L'utilizzo &egrave gratuito ed &egrave sufficiente la registrazione, semplice, veloce e gratuita.
		Ogni utente registrato dispone di una propria home page con il controllo dei propri blog ed il newsfeed dei propri amici, con la possibilità di interagire, commentare ed arrichire la propria esperienza.
	</p>
		
  <h1>Dove Siamo</h1><br>
  <iframe width="638" height="525" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684&amp;output=embed"></iframe><br /><small><a href="http://maps.google.it/maps?f=q&amp;source=embed&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684" style="color:#0000FF;text-align:left">Visualizzazione ingrandita della mappa</a></small>
  </center>
         
</div>
</div>
